version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: qenem
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: QEnem
    ports:
      - 5432:5432
    networks:
      - app_db
    hostname: db
    container_name: db
networks:
  app_db: