version: "3.9"

services:
  bd:
    image: postgres:latest
    container_name: postgres-bd
    networks:
      - app_db
    environment:
      - POSTGRES_PASSWORD=rootroot
  app:
    depends_on:
      - mensageria
      - bd
    image: kenadaraujo/teste:1.0 # Mudar esta linha
    container_name: app
    networks:
      - app_db
    ports:
      - 9000:9000
networks:
  app_db: